<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net6.0;net8.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.IO.Hashing" Version="8.0.0" />
    </ItemGroup>

    <PropertyGroup>
        <PackageId>Ddth.Signum</PackageId>
        <PackageVersion>0.0.0</PackageVersion>
        <Title>Ddth.Signum</Title>
        <Authors>DDTH;btnguyen2k</Authors>
        <Description>Lightweight .NET library for calculating checksums and object fingerprints.</Description>
        <PackageTags>checksum, fingerprint, utility</PackageTags>
        <PackageProjectUrl>https://github.com/DDTH/Ddth.Signum</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Copyright>Copyright (c) 2026 DDTH/Thanh Ba Nguyen</Copyright>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <PropertyGroup>
        <RepositoryUrl>https://github.com/DDTH/Ddth.Signum</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>

    <PropertyGroup>
        <PackageReleaseNotes>${RELEASE-NOTES}</PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../README.md" Pack="true" PackagePath="" />
        <None Include="../LICENSE.md" Pack="true" PackagePath="" />
        <None Include="../RELEASE-NOTES.md" Pack="true" PackagePath="" />
    </ItemGroup>

</Project>
